///////////////////////////////////////////////////////////
//  SerialCommuniPort.cs
//  Implementation of the Class SerialCommuniPort
//  Generated by Enterprise Architect
//  Created on:      08-七月-2009 15:36:47
//  Original author: LiZhL
///////////////////////////////////////////////////////////



namespace Xdgk.Communi
{

    ///// <summary>
    ///// 串口通讯类
    ///// </summary>
    //public class SerialCommuniPort : CommuniPort
    //{

    //    public SerialCommuniPort()
    //    {

    //    }


    //}//end SerialCommuniPort
}